param(
  [Parameter(Mandatory = $true)]
  [string]$RequestPath,

  [Parameter(Mandatory = $true)]
  [string]$OutputPath
)

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

function Get-ToolPath {
  param([string]$Name)
  $cmd = Get-Command $Name -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $localBin = Join-Path $env:USERPROFILE ".local\bin\$Name.exe"
  if (Test-Path -LiteralPath $localBin) { return $localBin }
  return $null
}

function Get-MediaDuration {
  param([string]$Path)
  $ffprobe = Get-ToolPath "ffprobe"
  if (!$ffprobe) { throw "ffprobe not found." }
  $raw = & $ffprobe -v error -show_entries format=duration -of default=nw=1:nk=1 "$Path"
  if ($LASTEXITCODE -ne 0 -or !$raw) { throw "Could not read duration: $Path" }
  return [double]::Parse($raw.Trim(), [Globalization.CultureInfo]::InvariantCulture)
}

$request = Get-Content -LiteralPath $RequestPath -Raw -Encoding UTF8 | ConvertFrom-Json
$duration = Get-MediaDuration ([string]$request.audio_path)
$mid = [math]::Max(0.5, $duration / 2.0)

$result = [pscustomobject]@{
  provider = "mock-command"
  audio_path = $request.audio_path
  language = $(if ($request.language) { $request.language } else { "en" })
  text = "This is an audio only script generated by the command ASR adapter. This key segment should use authorized B-roll assets."
  segments = @(
    [pscustomobject]@{
      start_seconds = 0.0
      end_seconds = [math]::Round($mid, 3)
      text = "This is an audio only script generated by the command ASR adapter."
    },
    [pscustomobject]@{
      start_seconds = [math]::Round($mid, 3)
      end_seconds = [math]::Round($duration, 3)
      text = "This key segment should use authorized B-roll assets."
    }
  )
}

$dir = Split-Path -Parent $OutputPath
if ($dir) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
[System.IO.File]::WriteAllText($OutputPath, ($result | ConvertTo-Json -Depth 8), [System.Text.UTF8Encoding]::new($false))
